# Generated by Django 5.0 on 2023-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='course',
            field=models.CharField(choices=[('Mca', 'Mca'), ('B.E/B.tech', 'B.E/B.tech'), ('Bca', 'Bca'), ('Bsc', 'Bsc'), ('B.com', 'B.com'), ('Diploma', 'Diploma'), ('ITI', 'ITI')], max_length=255),
        ),
    ]
