# Generated by Django 5.0 on 2023-12-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_alter_registration_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
